name: SimpleChaos Java Build

on:
  push:
    branches: [ main ]
    paths:
      - 'SimpleChaos/java/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'SimpleChaos/java/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # ubuntu-latest, windows-latest, macos-latest
        jdk-version: [11]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk-version }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build SimpleChaos/java
      run: mvn -B install --file SimpleChaos/java/pom.xml

    - name: Build SimpleChaos/spring
      run: mvn -B install --file SimpleChaos/spring/pom.xml

    - name: Build SimpleChaos/spring-aop
      run: mvn -B install --file SimpleChaos/spring-aop/pom.xml

    - name: Build SimpleChaos/demo/java
      run: mvn -B install --file SimpleChaos/demo-applications/java-demo/pom.xml

    - name: Build SimpleChaos/demo/spring
      run: mvn -B install --file SimpleChaos/demo-applications/spring-demo/pom.xml

    - name: Build SimpleChaos/demo/spring-aop
      run: mvn -B install --file SimpleChaos/demo-applications/spring-aop-demo/pom.xml